import { Link, Stack, Typography } from "@mui/material";
import { Translate } from "../../nonview";

import CustomAlert from "../base/CustomAlert";
import OnlinePredictionIcon from "@mui/icons-material/OnlinePrediction";
import { useDataSlowContext } from "../../nonview/core/DataSlowProvider";
export function ProjectionAlert() {
  const data = useDataSlowContext();
  if (!data) {
    return null;
  }
  const { electionDisplay, entIdx, electionPrevious } = data;

  const entID = "LK";
  const { nResultsTotal, nResultsReleased } = electionDisplay.getReleaseStats(
    entID,
    entIdx,
    electionPrevious
  );

  const isComplete = nResultsReleased === nResultsTotal;

  if (isComplete) {
    return null;
  }

  return (
    <CustomAlert severity="warning">
      <Typography variant="body1">
        {Translate(
          "This projection is generated by a Machine Learning model using both current released results and historical data. The results have a 90% confidence level, meaning there's a 10% chance they may be incorrect. These are not official results and could differ significantly from the final outcome. For more details, please refer to the "
        )}
        <Link href="https://github.com/nuuuwan/prespoll">
          {Translate("Source Code")}
        </Link>
        {"."}
      </Typography>
    </CustomAlert>
  );
}

export default function ProjectionTitle() {
  const data = useDataSlowContext();
  if (!data) {
    return null;
  }
  const { electionDisplay, pdIdx, electionPrevious } = data;

  const entID = "LK";
  const { nResultsTotal, nResultsReleased } = electionDisplay.getReleaseStats(
    entID,
    pdIdx,
    electionPrevious
  );

  const isComplete = nResultsReleased === nResultsTotal;

  let title = "Final Result";
  if (!isComplete) {
    title = "Projected Final Result";
  }

  return (
    <Typography variant="h4" color="secondary">
      <Stack direction="row" gap={1} sx={{ alignItems: "center" }}>
        <OnlinePredictionIcon />

        {Translate(title)}
      </Stack>
    </Typography>
  );
}
