const PARTY_LIST_TUPLES = [
  ["ACMC", "All Ceylon Makkal Congress"],
  ["ACTC", "All Ceylon Tamil Congress"],
  ["AITC", "Ahila Ilankai Thamil Congress"],
  ["AITM", "All Island Tamil Makkal Congress"],
  ["CDUA", "Ceylon Democratic Unity Alliance"],
  ["CWC", "Central Workers' Congress"],
  ["DNA", "Democratic National Alliance"],
  ["DP", "Democratic Party"],
  ["DPLF", "Democratic People's Liberation Front"],
  ["DUNF", "Democratic United National Front"],
  ["ELJP", "Eksath Lanka Janarajaya Pakshaya"],
  ["EPDP", "Eelam People's Democratic Party"],
  ["EPRLF", "Eelam People's Revolutionary Liberation Front"],
  ["IND01_D04", "Independent"],
  ["IND01_D06", "Independent"],
  ["IND05_D10", "Independent"],
  ["ITAK", "Illankai Tamil Arasu Kachchi"],
  ["JHU", "Jathika Hela Urumaya"],
  ["JJB", "Jathika Jana Balawegaya"],
  ["JSP", "Jana Setha Peramuna"],
  ["JVP", "Janatha Vimukthi Peramuna"],
  ["LDA", "Lanka Democratic Alliance"],
  ["Liberal", "Liberal"],
  ["LSSP", "Lanka Sama Samaja Party"],
  ["MEP", "Mahajana Eksath Peramuna"],
  ["MNA", "Muslim National Alliance"],
  ["NC", "National Congress"],
  ["NDF", "New Democratic Front"],
  ["NLF", "NLF"],
  ["NMPP", "National Movement for People's Power"],
  ["NPP", "National People's Power"],
  ["NSSP", "Nawa Sama Samaja Party"],
  ["NUA", "National Unity Alliance"],
  ["OPPP", "Our Power of People Party"],
  ["PA", "People's Alliance"],
  ["SDPT", "Social Democratic Party of Sri Lanka"],
  ["SJB", "Samagi Jana Balawegaya"],
  ["SLFP", "Sri Lanka Freedom Party"],
  ["SLMC", "Sri Lanka Muslim Congress"],
  ["SLMP", "Sri Lanka Mahajana Pakshaya"],
  ["SLPF", "SLPF"],
  ["SLPP", "Sri Lanka Podujana Peramuna"],
  ["SMBP", "Sinhale Mahasammatha Bhoomiputra Pakshaya"],
  ["SU", "Sihala Urumaya"],
  ["TELO", "TELO"],
  ["TMTK", "Thamizh Makkal Tesiya Kootani"],
  ["TMVP", "Tamil Makkal Viduthalai Pulikal"],
  ["TNA", "Tamil National Alliance"],
  ["TULF", "Tamil United Liberation Front"],
  ["UNP", "United National Party"],
  ["UPA", "UPA"],
  ["UPF", "UPF"],
  ["UPFA", "United People's Freedom Alliance"],
  ["USA", "USA"],
  ["USP", "USP"],
];
export default PARTY_LIST_TUPLES;
