// Auto-generated by add_indices.py
import PARTY_TO_LONG_NAME from "./PARTY_TO_LONG_NAME";
import POLITICAL_PARTY_TO_COLOR from "./POLITICAL_PARTY_TO_COLOR";
import STYLE from "./STYLE";
import VERSION from "./VERSION";

export { PARTY_TO_LONG_NAME, POLITICAL_PARTY_TO_COLOR, STYLE, VERSION };
