// Auto-generated by add_indices.py
import POLITICAL_PARTY_TO_COLOR from "./POLITICAL_PARTY_TO_COLOR";
import STYLE from "./STYLE";
import VERSION from "./VERSION";

export { POLITICAL_PARTY_TO_COLOR, STYLE, VERSION };
