const PARTY_TO_SYMBOL = {
  //
  ACMC: 'Peacock',
  ACTC: 'Bicycle',
  AITM: 'Ship',
  AJP: 'Flag',
  APA: 'Water Tap',
  APP: 'Water Tap',
  //
  CPSL: 'Star',
  CWC: 'Cockerel',
  //
  DLF: 'Clock',
  DNA: 'Post Box',
  //  "DP": "Flaming Torch",
  DP: 'Pen',
  DPF: 'Ladder',
  DPLF: 'Anchor',
  DTNA: 'Conch Shell',
  DUA: 'Two Leaves',
  DUNF: 'Eagle',
  DVJP: 'Ear of Paddy',
  //
  EDF: 'Megaphone',
  ELPP: 'Cup',
  EPDP: 'Veena',
  EPRLF: 'Fish',
  //
  FPF: 'Helicopter',
  FSP: 'Sledge Hammer',
  //
  ITAK: 'House',
  JJB: 'Compass',
  //
  //  "JSP": "Coconut",
  JSP: 'Tractor',
  JPF: 'Car',
  //
  LDP: 'Book',
  LSSP: 'Key',
  //
  MEP: 'Cart Wheel',
  //
  NC: 'Horse',
  NDF: 'Coconut',
  //  "NDF": "Motor Car",
  NDMLP: 'Kettle',
  NFF: 'Panchaudaya',
  NFGG: 'Double Flag',
  NIF: 'Till',
  NLNP: 'Rabbit',
  NPP: 'Compass',
  //  "NPP": "Electric Bulb",
  NPPT: 'Electric Bulb',
  NSSP: 'Table',
  NSU: 'Bow and Arrow',
  NUA: 'Pigeon',
  //
  PA: 'Chair',
  PHU: 'Flower',
  PLF: 'Bell',
  PPP: 'Flower Bunch',
  PSA: 'Umbrella',
  PSP: 'Guitar',
  PUFA: 'Trophy',
  RJA: 'Pineapple',
  //
  SB: 'Medal',
  SBP: 'Envelope',
  SDPSL: 'Kite',
  SDPT: 'Candle',
  SEP: 'Pair of Scissors',
  SJB: 'Telephone',
  SJP: 'Sword',
  SLCP: 'Star',
  SLFP: 'Hand',
  SLLP: 'Kangaroo',
  SLMC: 'Tree',
  SLMP: 'Eye',
  SLP: 'Kangaroo',
  SLPP: 'Flower Bud',
  SLSP: 'Balloon',
  SP: 'Envelope',
  SPSL: 'Balloon',
  SPF: 'Umberella',
  //
  TELO: 'Light House',
  TMK: 'Deer',
  TMVP: 'Boat',
  TPA: 'Torch Light',
  TULF: 'Sun',
  //
  UCPF: 'Mammoty',
  UDV: 'Microphone',
  ULF: 'Canoe',
  UNA: 'Pair of Scales',
  UNFF: 'Banana Bunch',
  UNP: 'Elephant',
  UPA: 'Butterfly',
  UPP: 'Mobile Phone',
  URF: 'Pencil',
  USP: 'Tri-shaw',
  Till: 'Till',
  //
  WNF: 'Sickle',
  //  Independent Groups
  IND: 'TV',
  IND1: 'Black Board',
  IND2: 'Tyre',
  IND3: 'Syringe',
  IND4: 'Calculator',
  IND5: 'Football',
  IND6: 'Rossette',
  IND7: 'Jac Fruit',
  IND8: 'Feather',
  IND9: 'Conch',
  IND10: 'Motor Cycle',
  IND11: 'Horse Shoe',
  IND12: 'Kerosene Lamp',
  IND13: 'Table Fan',
  IND14: 'Spectacles',
  IND15: 'Cricket Bat',
  IND16: 'Gas Cylinder',
};

export default PARTY_TO_SYMBOL;
