const PARTY_TO_LONG_NAME = {
  ACTC: "All Ceylon Tamil Congress",
  AITC: "All India Tamil Congress",
  DPLF: "Democratic People's Liberation Front",
  EPDP: "Eelam People's Democratic Party",
  ITAK: "Illankai Tamil Arasu Kachchi",
  JJB: "Jathika Jana Balawegaya",
  JVP: "Janatha Vimukthi Peramuna",
  LSSP: "Lanka Sama Samaja Party",
  MEP: "Mahajana Eksath Peramuna",
  MNA: "Muslim National Alliance",
  NDF: "New Democratic Front",
  NMPP: "National Movement for People's Power",
  NPP: "National People's Power",
  NUA: "National Unity Alliance",
  PA: "People's Alliance",
  SJB: "Samagi Jana Balawegaya",
  SLFP: "Sri Lanka Freedom Party",
  SLMC: "Sri Lanka Muslim Congress",
  SLMP: "Sri Lanka Mahajana Pakshaya",
  SLPP: "Sri Lanka Podujana Peramuna",
  TMVP: "Tamil Makkal Viduthalai Pulikal",
  TULF: "Tamil United Liberation Front",
  UNP: "United National Party",
  UPFA: "United People's Freedom Alliance",
  JHU: "Jathika Hela Urumaya",
  SU: "Sihala Urumaya",
  OPPP: "Our People's Power Party",
  ACMC: "All Ceylon Makkal Congress",
  NC: "National Congress",
  AITM: "Akhila Ilankai Tamil Mahasabha",
};

export default PARTY_TO_LONG_NAME;
